version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir app
    ports:
      - "8080:8000"
    volumes:
      - ./backend:/app
      - ./backend/backups:/app/backups  # Mount backups directory to host
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_LOCAL_URL=mongodb://mongo:27017  # For backup service
      - DATABASE_NAME=temple_db
      - PRIMARY_DATABASE=local  # Enable backup features
      - WATCHFILES_FORCE_POLLING="true"
      - PYTHONUNBUFFERED="1"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:

