version: '3.8'

services:
  backend:
    build:
      context: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir app
    ports:
      - "8080:8000"
    volumes:
      - ./backend:/app
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - DATABASE_NAME=temple_db
      - USE_MINIO="false"
      - WATCHFILES_FORCE_POLLING="true"
      - PYTHONUNBUFFERED="1"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
